### ISSUE TITLE
Make available in NC 19/20

### ISSUE THREAD

**Issue by nursoda** [rullzer/twofactor_email#111]
I use this app "untested" in production NC19 since early betas, no issues. I just tested it in NC20b3 and there also no issue at all.  – Why is it still marked "incompatible" for versions beyond NC18?

**Comment by nursoda** [comment]
Hmmm, well, I spoke too soon: Although I've been sucessfully using it since NC19 betas, I could create a reproducible bug today. Since I don't have a 18 instance any more, I could not verify if it's there also. Steps to trigger the bug:

- install and activate twofactor_email (as untested app in NC 19)
- create a NEW user account
- log in as that new user and navigate to settings (OK) → security (error 500)

**Comment by happyreacer** [comment]
>     * log in as that new user and navigate to settings (OK) → security (error 500)

Have you set an emailadress for this user? I think i hade the same problem in Nextcloud 18 wehen the user have no emailadress in the user options

**Comment by nursoda** [comment]
> Have you set an emailadress for this user?

Good catch. Probably not. I assume you think of the email address set in settings/user, right? Because I cannot even set up an email address for the app since I cannot access the settings page where I would do just that.

Either way I consider this a bug: entering a settings dialog must not depend on an email address being set or not.

**Comment by ovpc** [comment]
No issue to report, apart from it getting disabled and marked as untested, after an NC update from 18.0.4 to 19.0.5. It seems to be working fine when re-enabled.

**Comment by nursoda** [comment]
I can confirm this for NC 20 also. I have multiple instances and users using it regularly without issues.
(There are constraints to that statement, see above.)

**Comment by miklobit** [comment]
Tested and OK with NC 20.0.2 (except this bug whis empty user email).

**Comment by nursoda** [comment]
Thanks, @rullzer!
