### ISSUE TITLE
Compatibility with NC18 and PHP 7.4

### ISSUE THREAD

**Issue by nursoda** [rullzer/twofactor_email#47]
Please make twofactor_email compatible to NC18 and PHP 7.4.

**Comment by vasyugan** [comment]
Today I found that Nexcloud now wants me to upgrade to version 18, which would disable the email provider. That's very unfortunate because several of my users rely on it. Does porting it to NC 18 involve a lot of work?

**Comment by nursoda** [comment]
I activated the untested ("incompatible") twofactor_email app and it works fine. Mind that it's marked permanently as "allowed" in config.php, so once a compatible release is there, you might want to remove this entry:
`  'app_install_overwrite' => 
  array (
    0 => 'twofactor_email',
  ),`

**Comment by vasyugan** [comment]
> I activated the untested ("incompatible") twofactor_email app and it works fine. Mind that it's marked permanently as "allowed" in config.php, so once a compatible release is there, you might want to remove this entry
> ` 'app_install_overwrite' => array ( 0 => 'twofactor_email', ),`

Thanks! Did the same. Hope this app will continue to be maintained, though...

**Comment by rullzer** [comment]
released a new version.
