### ISSUE TITLE
Compatibility with NextCloud 19

### ISSUE THREAD

**Issue by ShevT** [rullzer/twofactor_email#85]
Please make twofactor_email compatible to NC19.

**Comment by NewRedsquare** [comment]
The app is working for me as of 19.0.0.12

**Comment by StephanStanisic** [comment]
> The app is working for me as of 19.0.0.12

Can confirm as well.

**Comment by acsfer** [comment]
App works if servers was migrated, but not on fresh installs.

> App "Two Factor e-mail provider" cannot be installed because it is not compatible with this version of the server.

**Comment by gessel** [comment]
Thanks for the install trick! This app is absolutely fundamental to making 2 factor remotely viable.

**Comment by trev-dev** [comment]
Could we re-open this please? The current version of Nextcloud does not see this provider as "compatible" with it. The version numbers supported stop at Nextcloud 18.

I updated to 19 and realized that this app was disabled automatically and effectively broke logins for all of my users. I had to "enable an untested" app to get it working again. We need an up-to-date version to avoid this.

**Comment by ShevT** [comment]
> The version numbers supported stop at Nextcloud 18.

Two Factor e-mail provider 1.0.1 installed perfectly on NextCloud 19.0.2 and work. 
No compatibility issues reported during installation.

**Comment by trev-dev** [comment]
@ShevT Well for me, when I upgraded to Nextcloud 19,  Two Factor email was automatically disabled. If I had missed this detail, I and many other users would've been locked out.

https://github.com/rullzer/twofactor_email/pull/110
